# Generated by Django 4.0.6 on 2022-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_last', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
