apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
